[package]
name = "dash-mpd"
version = "0.6.2"
authors = ["Eric Marsden <eric.marsden@risk-engineering.org>"]
description = "Parse, serialize, download an MPD manifest for MPEG-DASH or WebM-DASH media streaming"
readme = "README.md"
repository = "https://github.com/emarsden/dash-mpd-rs"
license = "MIT"
keywords = ["video", "streaming", "MPD", "DASH", "MPEG"]
categories = ["multimedia", "multimedia::video", "parser-implementations"]
publish = true
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_with = "2"
quick-xml = { version = "0.26", features = ["serialize"] }
chrono = { version = ">=0.4.20", features = ["serde"] }
regex = ">=1.5.5"
thiserror = "1"
log = "0.4"
url = { version = "2", optional = true }
data-url = { version = "0.2", optional = true }
reqwest = { version = "0.11", default-features = false, features = ["blocking", "gzip", "brotli", "rustls-tls", "socks"], optional = true }
hyper = { version = "0.14.18", default-features = false, features = ["tcp", "http1", "http2", "client", "runtime"] }
backoff = { version = "0.4", optional = true }
tempfile = { version = "3", optional = true }
sanitise-file-name = { version = "1", optional = true }
ac-ffmpeg = { version = "0.17", optional = true }

[dev-dependencies]
env_logger = "0.10"
ffprobe = "0.3"
sha2 = "0.10"
hex-literal = "0.3"
colored = "2"
indicatif = "0.17"
clap = "4"

[features]
default = ["fetch"]
fetch = ["url", "data-url", "reqwest", "backoff", "tempfile", "sanitise-file-name"]
libav = ["ac-ffmpeg"]

[target.'cfg(unix)'.dependencies]
xattr = "0.2"
